# Generated by Django 4.2.6 on 2024-05-09 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppAgriClima", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estacao",
            old_name="Codigo",
            new_name="codigo",
        ),
        migrations.RenameField(
            model_name="estacao",
            old_name="Latitude",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="estacao",
            old_name="Longitude",
            new_name="longitude",
        ),
        migrations.RenameField(
            model_name="estacao",
            old_name="Nome",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="estacao",
            old_name="TipoEstacao",
            new_name="tipoEstacao",
        ),
    ]
