# Generated by Django 4.2.6 on 2024-05-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppAgriClima", "0002_rename_codigo_estacao_codigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estacao",
            name="fonte",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
